rvm:
  - 2.1.2
branches:
  only:
      - master
before_install:
  - sudo apt-get update
  - sudo apt-get install csh
  - sudo apt-get install libqt4-dev
  - "export DISPLAY=:99.0"
  - "export DB_HOST=localhost"
  - "export DB_USER=root"
  - "export DB_PASSWORD="
  - "export SEABASE_ENV=development"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - bundle exec rake db:reset
  - bundle exec rake seed SEABASE_ENV=test
script:
  - bundle exec rake

