version: '2'
services:
  app:
    build: .
    ports:
      - "0.0.0.0:9292:9292"
    volumes:
      - .:/app
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=""
      - DISPLAY=:99.0
    depends_on:
      - mysql
    command: /usr/bin/supervisord -c /app/config/docker/supervisord_dev.conf
  mysql:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
