version: '2'
services:
  app:
    build: .
    ports:
      - "0.0.0.0:9292:9292"
    volumes:
      - .:/app
    depends_on:
      - mysql
    command: bundle exec rackup -o 0.0.0.0
  mysql:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
