version: '2'
services:
  app:
    build: .
    image: encoflife/seabase
    ports:
      - "0.0.0.0:80:80"
    env_file:
      - config/seabase-production.env
    volumes:
      - /opt/seabase/log/nginx:/var/log/nginx
      - /opt/seabase/log/app:/app/log
    depends_on:
      - mysql
    command: /usr/bin/supervisord -c /app/config/docker/supervisord.conf
  mysql:
    image: mysql:5.7
    volumes:
      - /opt/seabase/data/mysql:/var/lib/mysql
